
CREATE TABLE LOGIN_GROUP1(USERID VARCHAR2(10),
PASSWORD VARCHAR2(10) NOT NULL,ROLE VARCHAR2(10) NOT NULL,PRIMARY KEY(USERID));


INSERT INTO LOGIN_GROUP1 VALUES('admin','admin','admin');


INSERT INTO LOGIN_GROUP1 VALUES('customer','customer','customer');


INSERT INTO LOGIN_GROUP1 VALUES('CUST123','TCSHYD','customer');


DROP TABLE LOGIN_GROUP1;


update LOGIN_GROUP1 set PASSWORD='Hamd02' WHERE USERID='CUST123';

delete from LOGIN_GROUP1 WHERE PASSWORD='TCSHYD'





CREATE TABLE CUSTOMER_DETAILS_GROUP1
(CUSTOMERID VARCHAR2(10), PASSWORD VARCHAR2(10) NOT NULL,
NAME VARCHAR2(20) NOT NULL, AGE NUMBER(2) NOT NULL,
GENDER VARCHAR2(6) NOT NULL,LOCATION VARCHAR2(20) NOT NULL,EMAILID VARCHAR2(20) NOT NULL, PRIMARY KEY(CUSTOMERID));



CREATE TABLE CUSTOMER_DETAILS_GROUP1
(CUSTOMERID VARCHAR2(10) REFERENCES LOGIN_GROUP1(USERID) ON DELETE CASCADE, PASSWORD VARCHAR2(10) NOT NULL,
NAME VARCHAR2(20) NOT NULL, AGE NUMBER(2) NOT NULL,
GENDER VARCHAR2(6) NOT NULL,LOCATION VARCHAR2(20) NOT NULL,EMAILID VARCHAR2(20) NOT NULL,CONTACT_NUMBER VARCHAR2(10) NOT NULL, PRIMARY KEY(CUSTOMERID));

INSERT INTO CUSTOMER_DETAILS_GROUP1 VALUES('CUST123','Hamd02','Hamdan',24,'Male','Delhi','hamd@gmail.com');


DROP TABLE CUSTOMER_DETAILS_GROUP1;





CREATE TABLE ROOM_REQUEST_GROUP1
(REQUESTID VARCHAR2(10) PRIMARY KEY,
CUSTOMERID VARCHAR2(10),
CHECKINDATE VARCHAR2(10) NOT NULL,CHECKOUTDATE VARCHAR2(10) NOT NULL,
NUMBEROFROOMSREQUIRED NUMBER(2),REQUESTEDROOMTYPE VARCHAR2(10) NOT NULL,
ACREQUIRED VARCHAR2(10) NOT NULL,REQUESTEDCATEGORY VARCHAR2(10) NOT NULL,
REQUESTSTATUS VARCHAR2(10) NOT NULL);


CREATE TABLE ROOM_REQUEST_GROUP1
(REQUESTID VARCHAR2(10) PRIMARY KEY,
CUSTOMERID VARCHAR2(10) REFERENCES CUSTOMER_DETAILS_GROUP1(CUSTOMERID) ON DELETE CASCADE,
CHECKINDATE VARCHAR2(10) NOT NULL,CHECKOUTDATE VARCHAR2(10) NOT NULL,
NUMBEROFROOMSREQUIRED NUMBER(2),REQUESTEDROOMTYPE VARCHAR2(10) NOT NULL,
ACREQUIRED VARCHAR2(10) NOT NULL,REQUESTEDCATEGORY VARCHAR2(10) NOT NULL,
REQUESTSTATUS VARCHAR2(10) NOT NULL);

INSERT INTO ROOM_REQUEST_GROUP1 VALUES('REQ1','CUST123','2014-04-16','2014-08-18',1,'Single','AC','Standard','PENDING');

DROP TABLE ROOM_REQUEST_GROUP1;



CREATE TABLE ROOM_DETAILS_GROUP1
(ROOMNUMBER NUMBER(3) PRIMARY KEY,FLOORNUMBER NUMBER(2) NOT NULL,
ROOMSTATUS VARCHAR2(10) NOT NULL,ROOMTYPE VARCHAR2(10) NOT NULL,
ACFACILITY VARCHAR2(10) NOT NULL,CATEGORY VARCHAR2(10) NOT NULL,
REQUESTID VARCHAR2(10) NOT NULL);




INSERT INTO ROOM_DETAILS_GROUP1 VALUES(1,1,'VACANT','Single','AC','Standard','EMPTY');


DROP TABLE ROOM_DETAILS_GROUP1;
